name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # تثبيت المتطلبات الأساسية
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk wget unzip python3-dev python3-pip

      # تثبيت Cython
      - name: Install Cython
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install cython==0.29.36  # يمكنك تحديد النسخة المناسبة

      # إعداد Android SDK
      - name: Set up Android SDK
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O cmdline-tools.zip
          mkdir -p $HOME/android-sdk/cmdline-tools
          unzip cmdline-tools.zip -d $HOME/android-sdk/cmdline-tools
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
          echo "export ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV
          echo "export PATH=$ANDROID_HOME/platform-tools:$PATH" >> $GITHUB_ENV
          echo "export PATH=$ANDROID_HOME/tools:$PATH" >> $GITHUB_ENV
          echo "export PATH=$ANDROID_HOME/tools/bin:$PATH" >> $GITHUB_ENV
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
          export PATH=$ANDROID_HOME/platform-tools:$PATH
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "build-tools;30.0.3" "platforms;android-29" "sources;android-29" "ndk;21.1.6352462"

      # تثبيت Buildozer
      - name: Install Buildozer
        run: |
          python3 -m pip install buildozer

      # بناء المشروع
      - name: Build with Buildozer
        run: |
          buildozer android debug
          ls -la ./bin

      # رفع ملف APK
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: Android APK
          path: ./bin/*.apk
