name: Build Kivy App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3 python3-pip python3-venv git openjdk-17-jdk \
            zlib1g-dev libffi-dev libssl-dev liblzma-dev libjpeg-dev libfreetype6-dev \
            libncurses5-dev libsqlite3-dev libgstreamer1.0-dev gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly \
            gstreamer1.0-libav gstreamer1.0-tools libmtdev-dev libx11-dev libxrandr-dev \
            libxi-dev libxext-dev mesa-utils
        pip install --upgrade pip setuptools cython virtualenv

    - name: Install Buildozer
      run: pip install buildozer

    - name: Build APK
      run: |
        cd story
        buildozer init
        buildozer android debug
